### ISSUE TITLE
How do you run `nix develop` with a non-bash builder?

### ISSUE THREAD

**Issue by ursi** [numtide/devshell#110]
I heard about `devshell` as a solution for running `bashInteractive` in your nix shell so you could get bash completion. Not wanting a whole new dependency and also wanting to understand how things work. I tried to see if I could do that on my own. I figured out "how" but when I run `nix develop` I get [this error](https://github.com/NixOS/nix/blob/525015be7f908876e04e8d99c26b9ba8d13fb5d7/src/nix/develop.cc#L132). But somehow you guys manage to get around it? I was hoping I could get an explanation of how you manage to do this, or just a link to the relevant code, thanks!

**Comment by zimbatm** [comment]
See https://github.com/numtide/devshell/blob/eac56f015b0975be3b725721503626e926b285e8/nix/mkNakedShell.nix#L34

That file also includes a very minimal and self-contained implementation that you can re-use!

**Comment by ursi** [comment]
Thanks! Seems I've a-b problem'd myself. I thought using `bashInteractive` was the key to getting bash completion to work, but it looks like it's more complicated than that.

**Comment by zimbatm** [comment]
There are two other things you need to do: load the bash-completions profile, and set XDG_DATA_DIRS to point to the buildEnv/share folder.

**Comment by ursi** [comment]
Thanks for the info :) I think I'm just gonna try to integrate devshell instead of reinventing the wheel!

**Comment by ursi** [comment]
@zimbatm I'm noticing bash completions for the packages I add to devshell aren't showing up. The ones that are already in my environment are still there - like git. but if I add `"nodejs"` to `devshell.toml` and try the `npm` completions, they don't work.

**Comment by ursi** [comment]
oh, yeah this is actually a bug. I'll put in a PR.

**Comment by zimbatm** [comment]
thanks!
