### ISSUE TITLE
Better integration with Github Actions

### ISSUE THREAD

**Issue by yusdacra** [numtide/devshell#133]
**Is your feature request related to a problem? Please describe.**
Github Actions don't persist shell environments between steps unless you make use of `$GITHUB_ENV` and `$GITHUB_PATH`.

**Describe the solution you'd like**
It would be useful if devshell had a way to echo the environment variables changed to `$GITHUB_ENV` and `$PATH` changes to `$GITHUB_PATH`. A way could be to `nix build .#devShell.system && ./result source-github` or similar.

**Describe alternatives you've considered**
Currently I echo the env variables manually. It's also possible to just iterate over `env`'s output and echo that to `GITHUB_ENV` I believe.

**Comment by zimbatm** [comment]
Did you try `./result env > $GITHUB_ENV` ? I think that would be enough to keep all the env vars for the next shell.

**Comment by yusdacra** [comment]
Oh, I didn't think about that... That looks like it does indeed work, thanks!

**Comment by zimbatm** [comment]
If you want to extend the manual, that would be really cool.
