### ISSUE TITLE
Project is missing a license

### ISSUE THREAD

**Issue by lourkeur** [numtide/devshell#138]
**Describe the bug**
No public license is provided to users.

**To Reproduce**
Look for a license.

**Expected behavior**
There is clear licensing information.

**System information**
All systems.

**Additional context**
In the absence of an explicit license, [authors do not grant any permission to anyone on their work.](https://choosealicense.com/no-permission/) Even if there is no intent to enforce, the uncertainty can hinder adoption. An explicit license can clear it up.

I suggest the MIT license or a similar license, at least for the Nix files in the project, since this appears to be common practice. The devshell-cli tool could be covered by a copyleft if desired.

**Comment by zimbatm** [comment]
thanks, that was an oversight. Fixed in bd86d3a2bb28ce4d223315e0eca0d59fef8a0a73
