### ISSUE TITLE
Current default MOTD causes errors

### ISSUE THREAD

**Issue by 06kellyjac** [numtide/devshell#14]
I get the following error with the default motd: `error: \u characters in JSON strings are currently not supported`
Probably the hammer
https://github.com/numtide/devshell/blob/827e007dd9ad7b670f05287d50247151dddd5ff0/options.nix#L107
I'm guessing this is a nix v2 limitation

Setting a custom motd fixed the issue.

Is this fix sufficient for now? Remove emoji until nix v3?

**Comment by 06kellyjac** [comment]
Ok there's already a PR for this issue. #12 
Looks like it was the `esc` var rather than the hammer

**Comment by blaggacao** [comment]
Presumably fixed by #24
