### ISSUE TITLE
commands.*.alias referenced in example but invalid

### ISSUE THREAD

**Issue by behaghel** [numtide/devshell#147]
Unless I missed something, the example in this line isn't meant to work:
https://github.com/numtide/devshell/blob/6385982011031e24f7e45ad270bc7e2f90ec0af0/modules/commands.nix#L165

While I am here, this example also seems to imply that using `pkgs.[pkg-name]` in the *package* attribute could work but I haven't had any luck with that either. The format of the example being JSON is also surprising for the newbie that I am.

**Comment by zimbatm** [comment]
thanks!
