### ISSUE TITLE
How to handle custom versions of packages

### ISSUE THREAD

**Issue by zimbatm** [numtide/devshell#15]
I do have some _custom_ packages for dev shells. For example _kustomize_ is a central devshell component to us, but it's been under ongoing heavy development and release activity for the past year or so. Sometimes the last monday's version does not include the latest required bux fixes.

The pace at which nixpkgs catches up &mdash; even though extraordinarily up to date &mdash; is still sometimes too slow for our use case.

It would be interesting to think of ways how plain nix packages could be plugged into a toml config-based approach and work together with this cli tool seamlessly.

I think devops-responsible persons do have sometimes similar problems: how to ship latest critical bugfixes in devop tools to all developers quickly

_Originally posted by @blaggacao in https://github.com/numtide/devshell/pull/13#issuecomment-699077959_

**Comment by zimbatm** [comment]
It's a good point. And also a deep topic. It might be possible to override some packages src and patches attributes but it's not going to work uniformly.

**Comment by blaggacao** [comment]
Do I read correctly that means an overlay approach? I have to admir, I havn't yet fully understood how it _actually_ works, but that can be a solution to the toml interface: bring your own nixpkgs. (_BYON_)

**Comment by zimbatm** [comment]
I'll have to try things out. It's a bit of a too deep topic for me to serialize everything in an issue. The question is, how practical is it. What happens on failure, is it debuggable.

**Comment by blaggacao** [comment]
What I ended up doing for now &mdash; I think this is ok for all needs.

```nix
let
  nixpkgs-src = import ./nixpkgs-src.nix;
  overlay = import ./overlays/overlay.nix;  # my overlay stuff
  pkgs = import nixpkgs-src {
    config = {};
    overlays = [ overlay ];
  };
  devshell = pkgs.callPackage ( import ./devshell-src.nix ) { };
  # Overlays
  customTools = with pkgs; [
    commitizen
    container-structure-test
    kube-score
    skaffold-nix-builder
  ];
in
devshell {
  packages = customTools;
}
```

A possible toml interface would be:
```toml
[main]
pkgs-overlay = overlay.nix
```

**Comment by blaggacao** [comment]
I think https://github.com/numtide/devshell/commit/b84729196bdb967f2b96d312a9c6d285cd7fea23 would close this?

**Comment by zimbatm** [comment]
Indeed.
