### ISSUE TITLE
Is there a way to refer to the root of the directory?

### ISSUE THREAD

**Issue by noib3** [numtide/devshell#159]
**Is your feature request related to a problem? Please describe.**

I'm using devshell inside a flake for an Android app project. When I build the app from the command line I have to use a `/gradlew` script located in the root of the repository, which is annoying if I'm in another directory because I have to specify the relative path explicitely.

**Describe the solution you'd like**

I could add the root directory to the `PATH` but I'd rather add `gradlew` to the `commands` list with something like

```nix
commands = [
  {
    help = "Gradlew script";
    name = "gradlew";
    command = ''${root_dir}/gradlew "$@"'';
  }
];
```

is this already possible?

**Comment by zimbatm** [comment]
Yes, that's possible by using the $PRJ_ROOT environment variable. That variable is not available at build time because it would vary between machines.

**Comment by Yajo** [comment]
FTR that's veeery hidden [in the docs](https://numtide.github.io/devshell/modules_schema.html#env):

![imagen](https://user-images.githubusercontent.com/973709/154917133-98ec7737-768b-44ad-a72e-55d43e5dc6e5.png)

**Comment by Yajo** [comment]
Oh sorry, it's in the README:

https://github.com/numtide/devshell/blob/7033f64dd9ef8d9d8644c5030c73913351d2b660/README.md?plain=1#L51

The readme doesn't appear in the docs FWIW.

**Comment by zimbatm** [comment]
yeah, the docs are missing usage-driven scenarios. It's the kind of activity that is best done by hiring somebody for it I think.
