### ISSUE TITLE
Revise devshell design in light of https://zimbatm.com/notes/1000-instances-of-nixpkgs

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#162]
I hope we can kick off a discussion on how the design of the beloved `numtide/devshell` could be revised in light of https://zimbatm.com/notes/1000-instances-of-nixpkgs which I very much favor.

Let's have a discussion first and then maybe gather momentum for an implementation?

**Comment by zimbatm** [comment]
Generally, I see 3 ways to avoid instances of nixpkgs with flakes:

### Default option

For packages, use `nixpkgs.legacyPackages.${system}` in your flake and rely on the parent flake setting the "follows" to use the same instance of nixpkgs. This is the simplest approach. One downside is that you can't pass your own instance of nixpkgs around anymore. If all you did previously was extend nixpkgs with overlays that's fine. But if you patched nixpkgs or set config options such as `allowUnfree` (side note; we should create a nixpkgs-unfree repo that mirrors nixpkgs but with `allowUnfree` set to true), this approach is limiting. Nonetheless, I think this should be the default approach.

### Inputs constructor

For devshell, mkShell is actually a constructor. As a user, I think the expectation is that you can use your own inputs and overrides. Especially with `devshell.toml`, a current limitation is that only inputs from nixpkgs can be used. What we want is to somehow inject all the packages from all the inputs for the current system.

```nix
inputs@{ self, nixpkgs, treefmt, devshell }:
{
  devShell.x86_64-linux = devshell.mkShell2
    { 
      packages = { // devshell could propose devshell.lib.packageFromInputs to make that shorter.
        nixpkgs = nixpkgs.legacyPackages.${system};
        treefmt = treefmt.packages.${system};
      };
      configuration = {
        packages = [
          # now packages take a prefix, compatible with devshell.toml
          "treefmt.treefmt"
          "nixpkgs.hello"
        ];
     };
  };
} 
```

### Also export an overlay

As the last resort, a flake could also export an overlay of itself.
