### ISSUE TITLE
`setupHook`s handling

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#164]
Setup-Hook is ignored:

```bat
───────┬────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: /nix/store/zha6h1j6zpv655y2gwjxq1yh1dx8mfr4-source/pkgs/development/web/nodejs/setup-hook.sh
───────┼────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ addNodePath () {
   2   │     addToSearchPath NODE_PATH $1/lib/node_modules
   3   │ }
   4   │
   5   │ addEnvHooks "$hostOffset" addNodePath
───────┴────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Hence to use `prettier-plugin-toml`, this work around is necessary:
```nix
{
devshell.startup.nodejs-setuphook =
  nixpkgs.lib.stringsWithDeps.noDepEntry
    ''
    export NODE_PATH=${ nixpkgs.nodePackages.prettier-plugin-toml }/lib/node_modules:$NODE_PATH
    ";
}
```
 
 Would setuphook be honored, `packages = [ nixpkgs.nodejs ];` would do.
 
 _Is it worth considering adding a feature that loads eventual setup hooks in order to align further with upstream `mkShell`?_
 
 ---
 
<sub>Link to the full beauty:
 https://github.com/kamadorueda/alejandra/pull/15/files#diff-206b9ce276ab5971a2489d75eb1b12999d4bf3843b7988cbe8d687cfde61dea0R101-R105</sub>

**Comment by zimbatm** [comment]
This is not possible without bringing all of the stdenv and polluting the argument in.

**Comment by blaggacao** [comment]
OK, too bad. I almost suspected this.
