### ISSUE TITLE
Overlay is broken

### ISSUE THREAD

**Issue by tadfisher** [numtide/devshell#167]
**Describe the bug**

Since changing the `pkgs` parameter to `nixpkgs` in default.nix, the overlay is broken.

**To Reproduce**

1. Update a flake using devshell
2. Observe an error:

```shellsession
error: anonymous function at /nix/store/d4m6hpyv09n5k4x65mcxpsdxrdy0crfp-source/default.nix:1:1 called with unexpected argument 'pkgs'

       at /nix/store/d4m6hpyv09n5k4x65mcxpsdxrdy0crfp-source/overlay.nix:4:14:

            3| {
            4|   devshell = import ./. { pkgs = final; };
             |              ^
            5| }
```

**Expected behavior**

`overlay.nix` should pass `nixpkgs` instead of `pkgs`.

Alternatively, a way to call `mkShell` without requiring a nixpkgs overlay could be documented.

**Comment by zimbatm** [comment]
thanks
