### ISSUE TITLE
Support shell hooks

### ISSUE THREAD

**Issue by noib3** [numtide/devshell#181]
Does devshell support something like `mkShell`'s `shellHook` feature?

My personal use case would be to update a flutter project's android sdk path with `${pkgs.flutter}/bin/flutter config --android-sdk ${ANDROID_SDK_ROOT}` every time I enter the development environment.

**Comment by jfroche** [comment]
You can configure startup shell hooks using `devshell.startup` [module option](https://github.com/numtide/devshell/blob/master/modules/devshell.nix#L162-L169).
Example:
```nix
devshell.mkShell {
  devshell.startup.setup_sdk_path.text = "${pkgs.flutter}/bin/flutter config --android-sdk $ANDROID_SDK_ROOT";
}
```
