### ISSUE TITLE
suggested `git clone` fails

### ISSUE THREAD

**Issue by permezel** [numtide/devshell#185]
**Describe the bug**

Following the docs:
```console
Clone this repository, and enter into it:

$ git clone https://github.com/nix-community/todomvc-nix/tree/flake
$ cd todomvc-nix
```
This fails because the URL is invalid.

**To Reproduce**

1. git clone https://github.com/nix-community/todomvc-nix/tree/flake

**Expected behavior**

Typically, `git` command clones the repo.

Instead, I get:
```zsh
%  git clone https://github.com/nix-community/todomvc-nix/tree/flake 

Cloning into 'flake'...
fatal: repository 'https://github.com/nix-community/todomvc-nix/tree/flake/' not found
```
**System information**

 System Version:	macOS 12.3 (21E230)
  Kernel Version:	Darwin 21.4.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
...
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	9 days 7:22

```zsh
% nix --version
nix (Nix) 2.7.0
```
**Additional context**

**Comment by jfroche** [comment]
That's a bug in the README indeed. I fixed it here: https://github.com/nix-community/todomvc-nix/pull/32/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R105
Use the master branch using `git clone https://github.com/nix-community/todomvc-nix.git`
