### ISSUE TITLE
fails to build on darwin

### ISSUE THREAD

**Issue by permezel** [numtide/devshell#186]
**Describe the bug**

See #185 for companion bug.
After adjusting the URL so that the `git clone` succeeds, I move onto the next step, which also fails.

**To Reproduce**

Following the `Readme.md`, but fixing the URL:

1. git clone https://github.com/nix-community/todomvc-nix
2. cd todomvc
3. nix develop
This fails with:
```zsh
%  git clone https://github.com/nix-community/todomvc-nix           
Cloning into 'todomvc-nix'...
remote: Enumerating objects: 1165, done.
remote: Counting objects: 100% (763/763), done.
remote: Compressing objects: 100% (426/426), done.
remote: Total 1165 (delta 341), reused 649 (delta 250), pack-reused 402
Receiving objects: 100% (1165/1165), 9.83 MiB | 2.42 MiB/s, done.
Resolving deltas: 100% (516/516), done.
sloth% cd todomvc-nix 
sloth% nix develop
error: flake 'git+file:///Users/dap/proj/todomvc-nix' does not provide attribute 'devShells.x86_64-darwin.default', 'devShell.x86_64-darwin', 'packages.x86_64-darwin.default' or 'defaultPackage.x86_64-darwin'
       Did you mean devShell
```

**Expected behavior**

**System information**

Same as in #185.

**Additional context**

**Comment by jfroche** [comment]
This error is related to the nix-community/todomvc-nix repo, you can fill in an issue here instead: https://github.com/nix-community/todomvc-nix/issues
