### ISSUE TITLE
Support pre-push githook natively

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#19]
#18 provides for use cases of _pre-**push**_ hooks specifically. https://github.com/numtide/devshell/issues/16#issuecomment-700149605 provides analysis for why a lightweight implementation is superior beyond the mere benefit of being leightweight.

That means, the consolidated intended use case does not require git workdir management. What's worse, providing such would induce misinterpretations about the consolidated intended use case.

Therefore, it is proposed for _devshell_ to arrange for:

- A simple command sequence
  - that is defined in devshell's standard interfaces
  - and that is executed in order
  - in the context of the repo's root and within debshell env
  - by a devshell library facility
  - which is symlinked to `.git/hooks/pre-push`.

- The facility is capable of detecting modified files against the reference git ref, 
  - which in the case of pre-push
  - is origin's HEAD.

- The facility passes the modified files list
  - as last variadic argument
  - to each command in the list.

- The command itself needs to arrange for 
  - handling this variadic last argument (discarding if necessary),
  - filtering on file types against this variadic last argument
    - _devshell_ may provide a configurable generic wrapper script for filtering, that supports configurable matching through:
       - regex include
       - regex exclude
       - as well as [`identify`](https://github.com/pre-commit/identify)

**Comment by zimbatm** [comment]
The `git.hooks` extra module now allows to build on top of it.
