### ISSUE TITLE
Way to customize promt in useful manners

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#20]
https://github.com/numtide/devshell/blob/8850638db70cda50210a5152b1d555b9a520c8e0/default.nix#L119

Trying to put together a gitops (mono-)repo cli-driver from composable pieces, including _devshell_, I'd like to apply [project specific customization](https://github.com/jonmosco/kube-ps1) to the command prompt.

**Comment by blaggacao** [comment]
After thinking for a while, I might just implement this ortogonal in _direnv_. If you agree @zimbatm , please feel free to close.

**Comment by blaggacao** [comment]
https://github.com/numtide/devshell/blob/8850638db70cda50210a5152b1d555b9a520c8e0/options.nix#L151-L159

**Comment by zimbatm** [comment]
I'm not against adding an explicit PS1 option. It might be easier to figure out than using `bash.interactive`.

**Comment by blaggacao** [comment]
Ok, valid. I think that represents an integral vision about a proper devshell and might be the right kind of nusging feature.

There are caveats (you probably already know):

- different shells use different escape codes to mark non-consuming chars when calculating the tty width or other ways to declare single chars that cobsume multiple positions.
- zsh has `RPROMPT` which reflects the rightmost side of the tty.

**Comment by zimbatm** [comment]
I think that PS1 is relatively cross-shell compatible but it's to be verified.

Potentially each shell could have its own section in the configuration, but that leads to a multiplication of configuration for each project.

**Comment by blaggacao** [comment]
Oh I didn't know that. It looks like the escape chars are still different.

![image](https://user-images.githubusercontent.com/7548295/94742566-84267a00-033b-11eb-86b9-03056df7b891.png)

**Comment by zimbatm** [comment]
It looks like a big headache to be honest :sweat_smile:

**Comment by blaggacao** [comment]
Yes! &mdash; be it the desert. And I'm saying that because there is not always desert. 😉

**Comment by zimbatm** [comment]
It's possible to override the PS1 like this now:
```toml
[devshell.interactive.PS1]
text = "PS1='hello $ '"
```
It's not very user-friendly and only works in bash.
