### ISSUE TITLE
Support .overrideAttrs

### ISSUE THREAD

**Issue by yajo** [numtide/devshell#200]
**Is your feature request related to a problem? Please describe.**

Most of my devshells share a common base. I don't want to repeat it constantly.

**Describe the solution you'd like**

I'd like to be able to include a remote devshell and [call its `.overrideAttrs` function, just like with almost any package from nixpkgs](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideAttrs).

**Describe alternatives you've considered**

Use `devShells.default = pkgs.lib.makeOverridable pkgs.devshell.mkShell defaults` on the common shell. But that only gives me access to [`.override`](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-override) and [`.overrideDerivation`](https://nixos.org/manual/nixpkgs/stable/#sec-pkg-overrideDerivation). Both of those are less powerful than `.overrideAttrs` (the linked docs explain why).

**Additional context**

Of course, it's `stdenv.mkDerivation` that supplies the `.overrideAttrs` extension, and devhsell is deliberately not using that:

https://github.com/numtide/devshell/blob/a00abaeb902ff568f9542d4b6f335e3a4db5c548/README.md?plain=1#L28-L37

So it would be nice to provide an alternative.

**Comment by zimbatm** [comment]
Because we're using the module system, a better way to handle this would be to expose the devshell module in the parent flake, and then import it in the child flake. This is already possible today.

```
devShells.default = pkgs.devshell.mkShell {
  imports = [ pkgs.otherflake.devshellModules.default ];
}
```

**Comment by blaggacao** [comment]
@yajo you may find this pattern useful, we have several "devshell capsules" that we mix and match via the described module system: https://github.com/input-output-hk/devshell-capsules

**Comment by yajo** [comment]
Sorry for the long delay, I got other prioritary things to do. I just tested https://github.com/numtide/devshell/issues/200#issuecomment-1139680449 and it works pretty well. Thank you!
