### ISSUE TITLE
Prompt with custom shell functions

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#22]
```nix
{
  bash = {

    extra = ''
    # kube-ps1 context & namespace prompt
    source $(which kube-ps1)  # doesn't run in the final shell
    echo Run: $(tput bold; tput setaf 3)source '$(which kube-ps1)'$(tput sgr0)
    export RPROMPT='$(kube_ps1)'
    '';
  };
}
```
I want to elide to ask the user to manually run:

```shell
$ source $(which kube-ps1)
```

The shell function `kube_ps1` is not loaded into the final shell using either `direnv` or plain `nix-shell`.
Is this only supposed to work with `nix develop` ?

It looks as if the following trampoline was arranged for this use case, though:

https://github.com/numtide/devshell/blob/8850638db70cda50210a5152b1d555b9a520c8e0/default.nix#L213-L227

&rarr; [`kube-ps1`](https://github.com/jonmosco/kube-ps1/blob/master/kube-ps1.sh)

**Comment by Rizary** [comment]
For custom prompt, maybe `bash.interactive` [here](https://github.com/numtide/devshell/blob/master/options.nix#L151) is more preferable?

**Comment by blaggacao** [comment]
@Rizary It does not behave differently, it is just run in rhe same rcfile later on and within an if clause. Whats more when using direnv this if clause is not triggered. So unfortunately that alone doesn't solve the problem (yet).

**Comment by blaggacao** [comment]
Replaced by a more generic #25
