### ISSUE TITLE
Expose `flakeModule` from flake for use with `flake-parts`

### ISSUE THREAD

**Issue by srid** [numtide/devshell#238]
Is there any interest in providing a `flake-parts` module? @roberth had a WIP solution here: https://github.com/numtide/devshell/compare/master...hercules-ci:devshell:flake-modules

I'm happy to resume/update this if there is any interest.

[Matrix discussion](https://matrix.to/#/!gcrYWdPsIUOFpXFDHB:matrix.org/$f6D30PYnTtYwXgCSkcL7Vnw-xTg1-EMTfM1OZ8BycX8?via=matrix.org&via=ukvly.org&via=valkor.net)

My intention is to use devshell's MOTD feature but without having to create devshell.toml and the like (ie., configure everything in flake.nix, and use with an existing language dev shell). To begin with, I'd use this to replace all the scripts in https://github.com/srid/haskell-template/tree/master/bin

**Comment by zimbatm** [comment]
I like it. Especially if it can get the same treatment as with treefmt-nix.

**Comment by terlar** [comment]
This would be really nice, now writing abstractions on top of shells using config from flake-parts is a bit tricky.

**Comment by brianmcgee** [comment]
> This would be really nice, now writing abstractions on top of shells using config from flake-parts is a bit tricky.

In the meantime here's a simple way that been bringing in devshell, might be useful:

```nix
{
  inputs,
  lib,
  ...
}: let
  importDevshellModule = name: {
    perSystem = import (inputs.devshell + "/modules/${name}");
  };
in {
  imports = [
    (importDevshellModule "env.nix") # allows us to define env variables
    (importDevshellModule "commands.nix") # allows us to define shell commands
    (importDevshellModule "devshell.nix") # the glue that binds
  ];

  config.perSystem = {
    pkgs,
    config,
    ...
  }: let
    # capture the devshell config generated for us by the devshell modules
    cfg = config.devshell;
  in {
    config = {
      # we need to create the data dir as this is typically done with devshells mkShell which we aren't using
      devshell.startup.create-datadir.text = ''
        mkdir -p $PRJ_DATA_DIR
      '';

      # define some useful env variables
      env = [
 		...
      ];

      # add some common commands
      commands = [
        ...
      ];

      # set our devshell
      devShells.default = cfg.shell;
    };
  };
}
```

In the next week or so I'm going to port this to a proper flake module for devshell.

**Comment by terlar** [comment]
Thank you, won't this put the `env.nix` and `commands.nix` options in the top level namespace? I wanted a more isolated solution and had a look at the currently proposed [devenv integration](https://github.com/cachix/devenv/pull/360). Based on this and also having tested it could look like this:
```nix
{
  lib,
  flake-parts-lib,
  ...
}: let
  inherit (flake-parts-lib) mkPerSystemOption;
  inherit (lib) mkOption types;
in {
  options = {
    perSystem = mkPerSystemOption ({
      config,
      pkgs,
      ...
    }: let
      devshellType =
        (lib.evalModules {
          modules = import ./modules/modules.nix {
            inherit lib pkgs;
          };
        })
        .type;
    in {
      options.devshell.shells = mkOption {
        type = types.lazyAttrsOf devshellType;
        default = {};
      };
      config.devShells = lib.mapAttrs (_name: devshell: devshell.devshell.shell) config.devshell.shells;
    });
  };
}
```

**Comment by brianmcgee** [comment]
Yeah I didn't really mind about polluting the globacl namespace, just getting something working. I like the proposal above
