### ISSUE TITLE
Badge

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#42]
[![Devshell Dev Environment](https://img.shields.io/badge/nix-devshell-success?logo=NixOS)](github.com/numtide/devshell)

```markdown
[![Devshell Dev Environment](https://img.shields.io/badge/nix-devshell-success?logo=NixOS)](github.com/numtide/devshell)
```

Maybe users want to label their repository as supporting devshell development environments. Should it be blue?

**Comment by blaggacao** [comment]
https://img.shields.io/badge/nix-devshell-blue?logo=NixOS&labelColor=ccc

**Comment by zimbatm** [comment]
nice :)

**Comment by zimbatm** [comment]
The green and blue don't mix well together in the first one so my choice would be on option (2). But I like the dark background on the nix side in the first one better.

**Comment by zimbatm** [comment]
thanks for your ideas. I added the second badge to the README
