### ISSUE TITLE
Found a ... dev service manager

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#47]
https://github.com/ttacon/glorious

&rarr; https://github.com/ttacon/glorious/issues/49

**Comment by zimbatm** [comment]
Nice. If possible, I think it's best if the service manager can be decoupled from devshell. But then make a recommendation for one that works well. Similar to the generic code formatter idea.

**Comment by blaggacao** [comment]
I think we can close this for now. (It's still on the record and accessible)
