### ISSUE TITLE
warning: shell level (1000) too high, resetting to 1

### ISSUE THREAD

**Issue by blaggacao** [numtide/devshell#50]
Hi @zimbatm , I encountered this error when using indirect package definitions via `[[commands]]`. In turn using plain `package`, the problem is not observable.

Do you have any clou?

```console
devshell git:(err-shell-level) ✗ stack
/nix/store/r3j288vpmczbl500w6zz89gyfa4nr0b1-bash-4.4-p23/bin/bash: warning: shell level (1000) too high, resetting to 1
/nix/store/r3j288vpmczbl500w6zz89gyfa4nr0b1-bash-4.4-p23/bin/bash: warning: shell level (1000) too high, resetting to 1
^C
```

Reproducible on my machine on this minimal branch: https://github.com/blaggacao/devshell/tree/err-shell-level

**Comment by zimbatm** [comment]
The issue is that the `name` and `command` are the same. This generates a script that calls itself:
```console
$ cat $(which stack)
#!/nix/store/r3j288vpmczbl500w6zz89gyfa4nr0b1-bash-4.4-p23/bin/bash
stack
```
I think you meant to use the "package" attribute instead of "command".

Also, it might be worth adding protection to devshell directly as I can see this being an easy mistake to make.

**Comment by blaggacao** [comment]
Thanks a  lot for your quick help!
