### ISSUE TITLE
adding package's to the environment

### ISSUE THREAD

**Issue by Rizary** [numtide/devshell#7]
sometimes I want to put `rustPlatform.rustcSRC` into `RUST_SRC_PATH`, so it will return the evaluated path.

maybe the implementation is like:
```
[env]
RUST_SRC_PATH="(rustPlatform.rustcSrc)"

```

I'm not sure it is possible in `toml`.

**Comment by 06kellyjac** [comment]
Yeah not sure how you'd do it in toml.
I don't see anything in the tests for the builtin that lets you nix from inside evaluate
https://github.com/NixOS/nix/blob/94f11d0a61bba15ff8a93f2de8d1883783c8c508/tests/lang/eval-okay-fromTOML.nix


This worked just using nix though:
```nix
{}:
# ...
{
  # ...
  env.RUST_SRC_PATH="${pkgs.rustPlatform.rustcSrc}";
}
```

Full `shell.nix`:
```nix
{ system ? builtins.currentSystem }:
let
  pkgs = import ./nix/nixpkgs.nix { inherit system; };
in
pkgs.mkDevShell {
  name = "something";
  motd = "otherthing";
  commands = [
    {
      name = "something";
      help = "this is help";
      command = "echo something";
    }
  ];
  env.RUST_SRC_PATH="${pkgs.rustPlatform.rustcSrc}";
  packages = [ ];
}
```

**Comment by Rizary** [comment]
@06kellyjac yeah I manage to do that also. However, the case that I am facing is wrt to this:
```
  shellHook = ''
    export GO111MODULE=on
    unset GOPATH GOROOT
  '';
```

unset GOPATH and GOROOT is essential so that my VSCode's go plugin can work.

**Comment by Rizary** [comment]
I think I am gonna use `mkDevShell` right now.
