### ISSUE TITLE
NIXPKGS_PATH is defined after the user variables

### ISSUE THREAD

**Issue by zimbatm** [numtide/devshell#86]
Because of how the module system works, the values in the top module are set before anybody else.

This causes an issue because a user might want to set the `NIX_PATH` to `nixpkgs:$NIXPKGS_PATH`, which is set after.

**Comment by zimbatm** [comment]
@infinisil do you know of a trick to control the module loading order? 

I tried moving the configuration at the end of this list but it doesn't seem to make a difference:
https://github.com/numtide/devshell/blob/72297414a5c04e1503999766434cdcae7b9e5325/modules/default.nix#L13

**Comment by Infinisil** [comment]
You can use `mkAfter`/`mkBefore` to control the order of definitions, like `config.myOption = mkAfter "someString"`

**Comment by zimbatm** [comment]
thanks!
